---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.operator.useClusterRBAC | ternary "ClusterRoleBinding" "RoleBinding" }} 
metadata:
  name: {{ include "carthago-op-jenkins.fullname" . }}-op-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.operator.useClusterRBAC | ternary "ClusterRole" "Role" }} 
  name: {{ include "carthago-op-jenkins.fullname" . }}-op-role
subjects:
  - kind: ServiceAccount
    name: service-account
    namespace: {{ $.Release.Namespace }}

{{- if not .Values.operator.useClusterRBAC }}
{{- range .Values.operator.watchedNamespaces }}
{{- if ne . $.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "carthago-op-jenkins.fullname" . }}-op-rolebinding
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "carthago-op-jenkins.fullname" . }}-op-role
subjects:
  - kind: ServiceAccount
    name: service-account
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
