{{- if .Values.jenkinsKubernetesAgentEnabled }}
  {{- $apiVersion := .Values.apiVersion }}
  {{- range $jenkinsKubernetesAgent := .Values.jenkinsKubernetesAgents}}
---
apiVersion: {{ $apiVersion }}
kind: JenkinsKubernetesAgent
metadata:
  name: {{ $jenkinsKubernetesAgent.name }}
  {{- with $jenkinsKubernetesAgent.labels }}
  labels: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $jenkinsKubernetesAgent.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $jenkinsKubernetesAgent.podSpec }}
  podSpec: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $jenkinsKubernetesAgent.properties }}
  properties: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $jenkinsKubernetesAgent.roleRef }}
  roleRef: {{- toYaml . | nindent 4}}
  {{- end }}
  {{- end }}
{{- end }}

