{{- if .Values.jenkinsKubernetesAgentEnabled }}
  {{- $apiVersion := .Values.apiVersion }}
  {{- range $jenkinsKubernetesAgent := .Values.jenkinsKubernetesAgents}}
---
apiVersion: {{ $apiVersion }}
kind: JenkinsKubernetesAgent
metadata:
  name: {{ $jenkinsKubernetesAgent.name }}
  {{- with $jenkinsKubernetesAgent.labels }}
  labels: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $jenkinsKubernetesAgent.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $jenkinsKubernetesAgent.podSpec }}
  podSpec: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $jenkinsKubernetesAgent.description }}
  description: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $jenkinsKubernetesAgent.executors }}
  executors: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $jenkinsKubernetesAgent.remoteRootDirectory }}
  remoteRootDirectory: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $jenkinsKubernetesAgent.usage }}
  usage: {{- toYaml . | nindent 4}}
  {{- end }}
  { { - with $jenkinsKubernetesAgent.tunnelConnectionThrough } }
  tunnelConnectionThrough: { { - toYaml . | nindent 4 } }
  { { - end } }
  { { - with $jenkinsKubernetesAgent.jvmOptions } }
  jvmOptions: { { - toYaml . | nindent 4 } }
  { { - end } }
  { { - with $jenkinsKubernetesAgent.roles } }
  roles: { { - toYaml . | nindent 4 } }
  { { - end } }
  {{- end }}
{{- end }}

