{{- if .Values.jenkinsGroovyScriptsEnabled }}
{{- $apiVersion := .Values.apiVersion }}
{{- range $jenkinsGroovyScript := .Values.jenkinsGroovyScripts}}
---
apiVersion: {{ $apiVersion }}
kind: JenkinsGroovyScript
metadata:
  name: {{ $jenkinsGroovyScript.name }}
  {{- with $jenkinsGroovyScript.labels }}
  labels: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $jenkinsGroovyScript.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $jenkinsGroovyScript.data }}
  data: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $jenkinsGroovyScript.secretRef }}
  secretRef: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $jenkinsGroovyScript.dependsOn }}
  dependsOn: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
