name: Verify that the  current chart can be deployed locally on minikube

env:
  HELM_VERSION: 3.7.0
  IMAGE_REGISTRY: operatorservice.azurecr.io
  OP_CHART_DIRECTORY: ./chart/op-svc-jenkins # should match repo's directory structure
  CRS_CHART_DIRECTORY: ./chart/op-svc-jenkins-crs # should match repo's directory structure
  OPERATOR_NAMESPACE: operator
  JENKINS_NAMESPACE: jenkins # should match 'jenkinsNamespace' field value in operator-service values.yaml

#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

on:
  push:
    branches:
      - chore/sc-451-helm-chart-tests-on-pr

jobs:
    verify-that-chart-can-be-deployoed:
      name: test that current chart can be deployed locally on minikube
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
          name: checkout repo

        - name: install helm
          run: |
            make helm-install HELM_VERSION=$HELM_VERSION

        - name: prepare and start local minikube cluster
          run: |
            sudo apt-get update
            sudo apt-get install socat
            sudo mkdir -p $HOME/.kube $HOME/.minikube
            sudo chown -R $USER $HOME/.kube $HOME/.minikube
            make minikube-start MINIKUBE_DRIVER='docker' MEMORY_AMOUNT=4096 CPUS_NUMBER=2

        - name: create namespaces for Jenkins and Operator
          run: |
            kubectl create ns $JENKINS_NAMESPACE
            kubectl create ns $OPERATOR_NAMESPACE

        - name: create secret with data for accessing image registry
          run: |
            kubectl create secret docker-registry token \
            --namespace $OPERATOR_NAMESPACE \
            --docker-server=$IMAGE_REGISTRY \
            --docker-username=${{ secrets.DEPLOYMENT_TEST_WORKFLOW_CUSTOMER_NAME }} \
            --docker-password=${{ secrets.DEPLOYMENT_TEST_WORKFLOW_ACR_PASSWORD }}

        - name: create license secret
          run: |
            cat <<EOF | kubectl apply -f -
            apiVersion: v1
            kind: Secret
            metadata:
              name: license
            stringData:
              clientName: ${{ secrets.DEPLOYMENT_TEST_WORKFLOW_CUSTOMER_NAME }}
              licenseKey: ${{ secrets.DEPLOYMENT_TEST_WORKFLOW_LICENSE_SECRET_KEY }}
            EOF

        - name: install operator-service chart
          run: |
            helm install operator-service $OP_CHART_DIRECTORY -f $OP_CHART_DIRECTORY/values.yaml -n $OPERATOR_NAMESPACE

        # todo: verify that Operator is up and running step
        - name: verify that Operator is up and running
          timeout-minutes: 3
          run: |
            READY=false
            while [ $READY ne true ]; do
              READY=$(kubectl get pods -n operator --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}' | \
              kubectl get pod -n operator -o custom-columns=":status.containerStatuses[0].ready")
            done

            kubectl get pods -n operator --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}' | \
            kubectl get pod -n operator -o custom-columns=":status.containerStatuses[0].ready"

            echo "Operator got ready! All good so far!"

        - name: install crs chart
          run: |
            helm install operator-service-crs $CRS_CHART_DIRECTORY -f $CRS_CHART_DIRECTORY/values.yaml -n $JENKINS_NAMESPACE

        # todo: verify that Jenkins is up and running step
        - name: verify that Jenkins is up and running
          run: |
            echo "I guess Jenkins is fine too"


